//
// MaintenancesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class MaintenancesAPI {
    /**

     - parameter _id: (path) Maintenance id 
     - parameter locale: (query) Two-letter language code (ISO 639-1)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getMaintenanceById(_id: String, locale: String? = nil, completion: @escaping ((_ data: SFInlineResponse2005Model?,_ error: Error?) -> Void)) {
        getMaintenanceByIdWithRequestBuilder(_id: _id, locale: locale).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /maintenances/{id}
     - Returns a Maintenance based on Id.
     - examples: [{contentType=application/json, example={
  "createdAt" : "createdAt",
  "serviceKeys" : [ "serviceKeys", "serviceKeys" ],
  "isCore" : true,
  "MaintenanceImpacts" : [ {
    "systemAvailability" : "systemAvailability",
    "createdAt" : "createdAt",
    "startTime" : "startTime",
    "id" : 6,
    "type" : "type",
    "updatedAt" : "updatedAt"
  }, {
    "systemAvailability" : "systemAvailability",
    "createdAt" : "createdAt",
    "startTime" : "startTime",
    "id" : 6,
    "type" : "type",
    "updatedAt" : "updatedAt"
  } ],
  "instanceKeys" : [ "instanceKeys", "instanceKeys" ],
  "id" : 0,
  "affectsAll" : true,
  "updatedAt" : "updatedAt"
}}]
     
     - parameter _id: (path) Maintenance id 
     - parameter locale: (query) Two-letter language code (ISO 639-1)  (optional)

     - returns: RequestBuilder<SFInlineResponse2005Model> 
     */
    open class func getMaintenanceByIdWithRequestBuilder(_id: String, locale: String? = nil) -> RequestBuilder<SFInlineResponse2005Model> {
        var path = "/maintenances/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "locale": locale
        ])

        let requestBuilder: RequestBuilder<SFInlineResponse2005Model>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter locale: (query) Two-letter language code ISO 639-1 code. If objects in response have any associated Localizations, the objects will also return fields with localized text. Depending on internal configuration, a default may be set.  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getMaintenanceEventTypes(locale: String? = nil, completion: @escaping ((_ data: [Any]?,_ error: Error?) -> Void)) {
        getMaintenanceEventTypesWithRequestBuilder(locale: locale).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /maintenances/eventTypes
     - Returns an array of maintenance imapct type fields.
     - examples: [{contentType=application/json, example=[ "{}", "{}" ]}]
     
     - parameter locale: (query) Two-letter language code ISO 639-1 code. If objects in response have any associated Localizations, the objects will also return fields with localized text. Depending on internal configuration, a default may be set.  (optional)

     - returns: RequestBuilder<[Any]> 
     */
    open class func getMaintenanceEventTypesWithRequestBuilder(locale: String? = nil) -> RequestBuilder<[Any]> {
        let path = "/maintenances/eventTypes"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "locale": locale
        ])

        let requestBuilder: RequestBuilder<[Any]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter locale: (query) Two-letter language code ISO 639-1 code. If objects in response have any associated Localizations, the objects will also return fields with localized text. Depending on internal configuration, a default may be set.  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getMaintenanceFields(locale: String? = nil, completion: @escaping ((_ data: [Any]?,_ error: Error?) -> Void)) {
        getMaintenanceFieldsWithRequestBuilder(locale: locale).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /maintenances/fields
     - Returns an array of Maintenance fields.
     - examples: [{contentType=application/json, example=[ "{}", "{}" ]}]
     
     - parameter locale: (query) Two-letter language code ISO 639-1 code. If objects in response have any associated Localizations, the objects will also return fields with localized text. Depending on internal configuration, a default may be set.  (optional)

     - returns: RequestBuilder<[Any]> 
     */
    open class func getMaintenanceFieldsWithRequestBuilder(locale: String? = nil) -> RequestBuilder<[Any]> {
        let path = "/maintenances/fields"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "locale": locale
        ])

        let requestBuilder: RequestBuilder<[Any]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter startTime: (query) Start time for Maintenance to return (ISO 8601) (optional)
     - parameter service: (query) Filter by impacted Services (case insensitive) (optional)
     - parameter instance: (query) Filter by impacted Instances (case insensitive) (optional)
     - parameter name: (query) Filter by Name (case insensitive) (optional)
     - parameter limit: (query) Limit for pagination (optional, default to 10000)
     - parameter offset: (query) Offset for pagination (optional, default to 0)
     - parameter sort: (query) Sort by property (optional)
     - parameter order: (query) Ordering of property (optional)
     - parameter locale: (query) Two-letter language code ISO 639-1 code. If objects in response have any associated Localizations, the objects will also return fields with localized text. Depending on internal configuration, a default may be set.  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getMaintenances(startTime: String? = nil, service: String? = nil, instance: String? = nil, name: String? = nil, limit: Double? = nil, offset: Double? = nil, sort: String? = nil, order: String? = nil, locale: String? = nil, completion: @escaping ((_ data: [Any]?,_ error: Error?) -> Void)) {
        getMaintenancesWithRequestBuilder(startTime: startTime, service: service, instance: instance, name: name, limit: limit, offset: offset, sort: sort, order: order, locale: locale).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /maintenances
     - Returns an array of Maintenance objects. Defaults to last 30 days.
     - examples: [{contentType=application/json, example=[ "{}", "{}" ]}]
     
     - parameter startTime: (query) Start time for Maintenance to return (ISO 8601) (optional)
     - parameter service: (query) Filter by impacted Services (case insensitive) (optional)
     - parameter instance: (query) Filter by impacted Instances (case insensitive) (optional)
     - parameter name: (query) Filter by Name (case insensitive) (optional)
     - parameter limit: (query) Limit for pagination (optional, default to 10000)
     - parameter offset: (query) Offset for pagination (optional, default to 0)
     - parameter sort: (query) Sort by property (optional)
     - parameter order: (query) Ordering of property (optional)
     - parameter locale: (query) Two-letter language code ISO 639-1 code. If objects in response have any associated Localizations, the objects will also return fields with localized text. Depending on internal configuration, a default may be set.  (optional)

     - returns: RequestBuilder<[Any]> 
     */
    open class func getMaintenancesWithRequestBuilder(startTime: String? = nil, service: String? = nil, instance: String? = nil, name: String? = nil, limit: Double? = nil, offset: Double? = nil, sort: String? = nil, order: String? = nil, locale: String? = nil) -> RequestBuilder<[Any]> {
        let path = "/maintenances"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "startTime": startTime, 
            "service": service, 
            "instance": instance, 
            "name": name, 
            "limit": limit, 
            "offset": offset, 
            "sort": sort, 
            "order": order, 
            "locale": locale
        ])

        let requestBuilder: RequestBuilder<[Any]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter startTime: (query) Start time for Maintenance to return (ISO 8601) (optional)
     - parameter isActive: (query) Active Maintenance (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getMaintenancesPreview(startTime: String? = nil, isActive: String? = nil, completion: @escaping ((_ data: [Any]?,_ error: Error?) -> Void)) {
        getMaintenancesPreviewWithRequestBuilder(startTime: startTime, isActive: isActive).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /maintenances/preview
     - Returns an array of Maintenance objects. Defaults to last 30 days.
     - examples: [{contentType=application/json, example=[ "{}", "{}" ]}]
     
     - parameter startTime: (query) Start time for Maintenance to return (ISO 8601) (optional)
     - parameter isActive: (query) Active Maintenance (optional)

     - returns: RequestBuilder<[Any]> 
     */
    open class func getMaintenancesPreviewWithRequestBuilder(startTime: String? = nil, isActive: String? = nil) -> RequestBuilder<[Any]> {
        let path = "/maintenances/preview"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "startTime": startTime, 
            "isActive": isActive
        ])

        let requestBuilder: RequestBuilder<[Any]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
