//
// SFBody7Model.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SFBody7Model: Codable {

    /** Email Address to Send Link to */
    public var emailAddress: String?

    public init(emailAddress: String?) {
        self.emailAddress = emailAddress
    }


}

