//
// SFFieldOptionModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SFFieldOptionModel: Codable {

    public var key: String?
    public var visible: Bool?

    public init(key: String?, visible: Bool?) {
        self.key = key
        self.visible = visible
    }


}

