//
// SFFieldModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct SFFieldModel: Codable {
    public var _id: Int?
    public var attribute: String
    public var fieldOptions: [SFIncidentsfieldsFieldOptionsModel]?

    public init(_id: Int?, attribute: String, fieldOptions: [SFIncidentsfieldsFieldOptionsModel]?) {
        self._id = _id
        self.attribute = attribute
        self.fieldOptions = fieldOptions
    }

    public enum CodingKeys: String, CodingKey {
        case _id = "id"
        case attribute
        case fieldOptions = "FieldOptions"
    }
}
