//
// SFInlineResponse404Model.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct SFInlineResponse404Model: Codable {
    public var message: String?

    public init(message: String?) {
        self.message = message
    }
}
