//
// SFMaintenanceEventTypeModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SFMaintenanceEventTypeModel: Codable {

    public var key: String?

    public init(key: String?) {
        self.key = key
    }


}

