//
// SFMaintenancesMaintenanceImpactsModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct SFMaintenancesMaintenanceImpactsModel: Codable {
    public var _id: Int?
    public var startTime: String?
    public var type: String?
    public var systemAvailability: String?
    public var createdAt: String?
    public var updatedAt: String?

    public init(_id: Int?, startTime: String?, type: String?, systemAvailability: String?, createdAt: String?, updatedAt: String?) {
        self._id = _id
        self.startTime = startTime
        self.type = type
        self.systemAvailability = systemAvailability
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey {
        case _id = "id"
        case startTime
        case type
        case systemAvailability
        case createdAt
        case updatedAt
    }
}
