//
// SFSubscribeSubscriptionsSeveritiesModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct SFSubscribeSubscriptionsSeveritiesModel: Codable {
    public var major: Bool?
    public var minor: Bool?
    public var maintenances: Bool?

    public init(major: Bool?, minor: Bool?, maintenances: Bool?) {
        self.major = major
        self.minor = minor
        self.maintenances = maintenances
    }
}
