//
// SFSubscribeSubscriptionsInstancesModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct SFSubscribeSubscriptionsInstancesModel: Codable {
    public var all: Bool?
    public var services: [String: SFSubscribeSubscriptionsServicesModel]?

    public init(all: Bool?, services: [String: SFSubscribeSubscriptionsServicesModel]?) {
        self.all = all
        self.services = services
    }
}
